import fellow
import typecheck

@fellow.app.task(name="graph.degree")
@typecheck.returns("100 * (string, count)")
def degree():
    return [('Alec Baldwin', 82)] * 100

@fellow.app.task(name="graph.pagerank")
@typecheck.returns("100 * (string, number)")
def pagerank():
    return [('Martha Stewart', 0.00019312108706213307)] * 100

@fellow.app.task(name="graph.best_friends")
@typecheck.returns("100 * ((string, string), count)")
def best_friends():
    result = [((u'Gillian Miniter\r', u'Sylvester Miniter\r'), 124),
 ((u'Bonnie Comley\r', u'Stewart Lane\r'), 87),
 ((u'Jamee Gregory\r', u'Peter Gregory\r'), 77),
 ((u'Andrew Saffir\r', u'Daniel Benedict\r'), 69),
 ((u'Dayssi Olarte\r', u'Kanavos\r'), 68),
 ((u'Geoffrey Bradfield\r', u'Roric Tobin\r'), 68),
 ((u'Jean Shafiroff\r', u'Martin Shafiroff\r'), 61),
 ((u'Barbara Tober\r', u'Donald Tober\r'), 59),
 ((u'Jonathan Farkas\r', u'Somers Farkas\r'), 56),
 ((u'Alexandra Lebenthal\r', u'Jay Diamond\r'), 54),
 ((u'Campion Platt\r', u'Tatiana Platt\r'), 52),
 ((u'Jonathan Tisch\r', u'Lizzie Tisch\r'), 48),
 ((u'John Catsimatidis\r', u'Margo Catsimatidis\r'), 48),
 ((u'Eleanora Kennedy\r', u'Michael Kennedy\r'), 45),
 ((u'Valentin Hernandez\r', u'Yaz Hernandez\r'), 44),
 ((u'Chris Meigher\r', u'Grace Meigher\r'), 44),
 ((u'Barbara Regna\r', u'Peter Regna\r'), 43),
 ((u'Chappy Morris\r', u'Melissa Morris\r'), 42),
 ((u'Elizabeth Stribling\r', u'Guy Robinson\r'), 40),
 ((u'Deborah Norville\r', u'Karl Wellner\r'), 39),
 ((u'Fernanda Kellogg\r', u'Kirk Henckels\r'), 37),
 ((u'David Koch\r', u'Julia Koch\r'), 37),
 ((u'Geary Ross\r', u'Wilbur Ross\r'), 37),
 ((u'Guardiola\r', u'Joanne\r'), 37),
 ((u'Couri Hay\r', u'Janna Bullock\r'), 33),
 ((u'Douglas Hannant\r', u'Frederick Anderson\r'), 32),
 ((u'Diane\r', u'Furstenberg\r'), 32),
 ((u'Arie Kopelman\r', u'Coco Kopelman\r'), 32),
 ((u'Richthofen\r', u'Sessa\r'), 30),
 ((u'Dennis Basso\r', u'Michael Cominotto\r'), 30),
 ((u'Charles Cohen\r', u'Clo Cohen\r'), 29),
 ((u'Hospital\r', u'Surgery\r'), 29),
 ((u'Cynthia Lufkin\r', u'Dan Lufkin\r'), 29),
 ((u'Leonel Piraino\r', u'Nina Griscom\r'), 28),
 ((u'Hearst McInerney\r', u'Jay McInerney\r'), 28),
 ((u'Donald Trump\r', u'Melania Trump\r'), 27),
 ((u'Dimitri\r', u'Yugoslavia\r'), 27),
 ((u'Johannes Huebl\r', u'Olivia Palermo\r'), 27),
 ((u'Oscar\r', u'Renta\r'), 27),
 ((u'Arlene Dahl\r', u'Marc Rosen\r'), 26),
 ((u'Hunt Slonem\r', u'Liliana Cavendish\r'), 25),
 ((u'Dee Ocleppo\r', u'Tommy Hilfiger\r'), 25),
 ((u'Chuck Scarborough\r', u'Ellen Scarborough\r'), 25),
 ((u'Alina Cho\r', u'John Demsey\r'), 25),
 ((u'James Mischka\r', u'Mark Badgley\r'), 25),
 ((u'Harry Slatkin\r', u'Laura Slatkin\r'), 24),
 ((u'Kathy Prounis\r', u'Othon Prounis\r'), 24),
 ((u'Richard Johnson\r', u'Sessa\r'), 24),
 ((u'Potter Aston\r', u'Sherrell Aston\r'), 24),
 ((u'Boni\r', u'Graziano\r'), 24),
 ((u'Jean Doyen\r', u'Michael Kovner\r'), 24),
 ((u'Hilary Ross\r', u'Wilbur Ross\r'), 23),
 ((u'Shirin\r', u'Wulffen\r'), 23),
 ((u'Donna Soloway\r', u'Richard Soloway\r'), 23),
 ((u'Marvin Davidson\r', u'Mary Davidson\r'), 22),
 ((u'Jeff Peek\r', u'Liz Peek\r'), 22),
 ((u'Countess LuAnn\r', u'Lesseps\r'), 22),
 ((u'Francine LeFrak\r', u'Rick Friedberg\r'), 22),
 ((u'Diana Taylor\r', u'Michael Bloomberg\r'), 22),
 ((u'Cancer Center\r', u'Society Center\r'), 22),
 ((u'David Lauren\r', u'Lauren Bush\r'), 22),
 ((u'John Wambold\r', u'Melanie Wambold\r'), 22),
 ((u'Jean Shafiroff\r', u'Patricia Shiah\r'), 21),
 ((u'Coleman Burke\r', u'Susan Burke\r'), 21),
 ((u'Gayle Sobel\r', u'Howard Sobel\r'), 21),
 ((u'Ingrid Connolly\r', u'John Connolly\r'), 21),
 ((u'Brian Stewart\r', u'Stephanie Krieger\r'), 21),
 ((u'Anna Safir\r', u'Eleanora Kennedy\r'), 21),
 ((u'Jean Shafiroff\r', u'Sharon Bush\r'), 21),
 ((u'Kathy Hilton\r', u'Rick Hilton\r'), 21),
 ((u'Ray Kelly\r', u'Veronica Kelly\r'), 21),
 ((u'Renee Steinberg\r', u'Richard Steinberg\r'), 21),
 ((u'CeCe Black\r', u'Lee Black\r'), 20),
 ((u'Naeem Khan\r', u'Ranjana Khan\r'), 20),
 ((u'Potter Aston\r', u'Somers Farkas\r'), 20),
 ((u'Richard Johnson\r', u'Sessa Johnson\r'), 20),
 ((u'Richard Johnson\r', u'Richthofen\r'), 20),
 ((u'Alex Lundqvist\r', u'Keytt Lundqvist\r'), 20),
 ((u'Gillian Miniter\r', u'Serena Miniter\r'), 19),
 ((u'Isabel Toledo\r', u'Ruben Toledo\r'), 19),
 ((u'Marcia Mishaan\r', u'Richard Mishaan\r'), 19),
 ((u'Geoffrey Thomas\r', u'Sharon Sondes\r'), 19),
 ((u'Robert Bradford\r', u'Taylor Bradford\r'), 18),
 ((u'Nicholas Scoppetta\r', u'Susan Magazine\r'), 18),
 ((u'Kim Taipale\r', u'Nicole Miller\r'), 18),
 ((u'Milstein Hall\r', u'Ocean Life\r'), 18),
 ((u'John Castle\r', u'John Connolly\r'), 18),
 ((u'Committee Co-chair\r', u'Committee Co-chair\r'), 18),
 ((u'Barbara\r', u'Portago\r'), 18),
 ((u'Andrew\r', u'Andrew\r'), 18),
 ((u'Bobby Zarin\r', u'Jill Zarin\r'), 18),
 ((u'Cece Black\r', u'Lee Black\r'), 17),
 ((u'Ann Rapp\r', u'Roy Kean\r'), 17),
 ((u'David Yanks\r', u'Samantha Yanks\r'), 17),
 ((u'Richthofen Johnson\r', u'Sessa Johnson\r'), 17),
 ((u'Heather Leeds\r', u'Tom Leeds\r'), 17),
 ((u'Tatiana Perkin\r', u'Thorne Perkin\r'), 17),
 ((u'Alec Baldwin\r', u'Hilaria Baldwin\r'), 17),
 ((u'Alexandra Lebenthal\r', u'Claudia Lebenthal\r'), 17),
 ((u'Judy Gilbert\r', u'Rod Gilbert\r'), 17),
 ((u'Harry Kargman\r', u'Jill Kargman\r'), 17)]

    return result
